# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3dd1ac5cb7aca0f74ff2590631c1a86ef3a8b62f805323f63fe525cd0aabf76989cd9118547032451239d7eec64ff661aebf170f1b6b4d73d65c3f2d1f571d8c

test:
  secret_key_base: c78c1bafb7452936d901a2b8761b6064e4abdc69bd5a597bc1acfb819bfc041a046912dfbcd7734c3c4fc1478d638f3c31231e0b62562b19136fa65f0fa74fd9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
